---
apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: camel-ose-springboot-xml
  spec:
    tags:
    - from:
        kind: ImageStreamImage
        name: camel-ose-springboot-xml@sha256:c01a5b8f03044d1cffb87234bc5de47f768c33f6c51ebea128ca2a21948ff076
        namespace: uscc
      name: latest
