---
apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: rest-split-transform-amq-lab
  spec:
    tags:
    - from:
        kind: ImageStreamImage
        name: rest-split-transform-amq-lab@sha256:b5e3619dd4cea06c0482afac49c8c80bec85c0ace7c51d34be5dfdffc7c99f9b
        namespace: user8-fuse
      name: 1.0.0
