---
apiVersion: v1
kind: Service
metadata:
  annotations:
    discovery.3scale.net/path: /rest
    discovery.3scale.net/discovery-version: v1
    discovery.3scale.net/scheme: http
    discovery.3scale.net/port: "8080"
    fabric8.io/git-commit: 0bf6049dbd18e18ab6c65ed4fcedadf9595f70c0
    fabric8.io/iconUrl: img/icons/camel.svg
    fabric8.io/git-branch: master
    prometheus.io/scrape: "true"
    prometheus.io/port: "9779"
  labels:
    expose: "true"
    discovery.3scale.net: "true"
    app: camel-ose-springboot-xml
    provider: fabric8
    version: 1.0.0-SNAPSHOT
    group: org.mycompany
  name: camel-ose-springboot-xml
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: camel-ose-springboot-xml
    provider: fabric8
    group: org.mycompany
